# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.srcs/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/design_1_hdmi_in_0_2.xci
# IP: The module: 'design_1_hdmi_in_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/dvi2rgb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dvi2rgb_0 || ORIG_REF_NAME==dvi2rgb_0} -quiet] -quiet

# IP: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_pixclk/ila_pixclk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_pixclk || ORIG_REF_NAME==ila_pixclk} -quiet] -quiet

# IP: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_refclk/ila_refclk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_refclk || ORIG_REF_NAME==ila_refclk} -quiet] -quiet

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_pixclk/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_pixclk || ORIG_REF_NAME==ila_pixclk} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_pixclk/ila_pixclk_ooc.xdc

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_timing_workaround.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==dvi2rgb_0 || ORIG_REF_NAME==dvi2rgb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/dvi2rgb.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==dvi2rgb_0 || ORIG_REF_NAME==dvi2rgb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/dvi2rgb_ooc.xdc

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_refclk/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_refclk || ORIG_REF_NAME==ila_refclk} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_refclk/ila_refclk_ooc.xdc

# IP: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.srcs/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/design_1_hdmi_in_0_2.xci
# IP: The module: 'design_1_hdmi_in_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/dvi2rgb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dvi2rgb_0 || ORIG_REF_NAME==dvi2rgb_0} -quiet] -quiet

# IP: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_pixclk/ila_pixclk.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_pixclk || ORIG_REF_NAME==ila_pixclk} -quiet] -quiet

# IP: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_refclk/ila_refclk.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_refclk || ORIG_REF_NAME==ila_refclk} -quiet] -quiet

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_pixclk/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_pixclk || ORIG_REF_NAME==ila_pixclk} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_pixclk/ila_pixclk_ooc.xdc

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_timing_workaround.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==dvi2rgb_0 || ORIG_REF_NAME==dvi2rgb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/dvi2rgb.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==dvi2rgb_0 || ORIG_REF_NAME==dvi2rgb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/dvi2rgb_ooc.xdc

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_refclk/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_refclk || ORIG_REF_NAME==ila_refclk} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/overcookedlobster/Documents/School/VLSI/Local_Maxima_Pynq/Local_Maxima_Pynq.gen/sources_1/bd/design_1/ip/design_1_hdmi_in_0_2/src/dvi2rgb_0/src/ila_refclk/ila_refclk_ooc.xdc
